version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=alplakes_api
      - POSTGRES_PASSWORD=alplakes_api
      - POSTGRES_DB=alplakes_api_dev

volumes:
  postgres_data:
